services:
  - type: web
    name: housekeeper-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m alembic upgrade head && python -m main
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WAREHOUSEMAN_ID
        sync: false
      - key: MANAGER_ID
        sync: false
      - key: ALLOWED_EMPLOYEE_IDS
        sync: false
        optional: true
      - key: TIMEZONE
        value: Europe/Moscow
      - key: LOG_LEVEL
        value: INFO
      - key: DATABASE_URL
        fromDatabase:
          name: housekeeper-db
          property: connectionString
        # Важно: заменить postgresql:// на postgresql+asyncpg:// в настройках Render

databases:
  - name: housekeeper-db
    databaseName: housekeeper_db
    user: housekeeper_user
    region: frankfurt
    plan: free

